### PR TITLE
Finish feature "futures-nightly" removal

### PR DESCRIPTION
**Pull request by EPashkin**
@GuillaumeGomez PR in high-probable case that https://github.com/gtk-rs/glib/pull/373 fails again

cc @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
Strange, but https://github.com/gtk-rs/glib/pull/373 builds fine without this.
Build failure is just network error.
IMHO better merge this anyway, but seems it also safe to just close this PR.
@sdroege, @GuillaumeGomez what you think?

**Comment by sdroege** [comment]
I wanted to keep as much as possible in place so it can easily be added back later, but I don't really care much. Whatever seems better to you :)

**Comment by GuillaumeGomez** [comment]
If it works, it works so sounds good to me.

**Comment by EPashkin** [comment]
Ok, I close this, as it don't break build, `gio_futures_await` still needed "futures-nightly".

**Comment by GuillaumeGomez** [comment]
I merge then.

**Pull request merged**
