### PR TITLE
Use new cairo surfaces API

### PR DESCRIPTION
**Pull request by EPashkin**
See https://github.com/gtk-rs/cairo/pull/146

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please replace ".unwrap()" calls with ".expect(...)".

**Comment by EPashkin** [comment]
Done. Although the examples do not contain any :wink:

**Comment by GuillaumeGomez** [comment]
Thanks! Just waiting for CIs confirmation.

**Comment by GuillaumeGomez** [comment]
Ah damn, I'll update them then.

**Pull request merged**
