### PR TITLE
Cleanup clone

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
:+1: 

So rustfmt actually formats the closure in the `clone!` macro?

**Comment by GuillaumeGomez** [comment]
Apparently?

**Comment by sdroege** [comment]
> Apparently?

Yeah, I'm surprised. Apparently it became more clever than before :)

**Comment by sdroege** [comment]
@GuillaumeGomez Green :)

**Pull request merged**
