### PR TITLE
Use `Result::expect` instead of checking `is_err`

### PR DESCRIPTION
**Pull request by Wallacoloo**
Identical to #133 but only fixes the examples in the `pending` branch.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
The problem with this solution is that it panics and makes an ugly output, so I don't like much. :-/

What do you think @EPashkin?

**Comment by EPashkin** [comment]
@Wallacoloo, Sorry I don't looked what really changed in previous PR.
I agree with @GuillaumeGomez that `expect` produce output, that unneeded in this case.
PS. All example targets is equals for both master and pending.

**Comment by Wallacoloo** [comment]
When it comes to writing example code, my opinion is that having idiomatic code is more important than pretty output (though I also don't find the output of panics to be ugly). Panics also point you directly to the source of the error (line number / source file), so again I think that's a useful thing to provide developers.

And for what it's worth, [one of the examples](https://github.com/gtk-rs/examples/blob/master/src/bin/child-properties.rs#L13) already panics on error.

This is all just opinions though - do as you see fit.

**Comment by GuillaumeGomez** [comment]
Closing due to inactivity. Don't hesitate to reopen once updated. :)

**Pull request closed without merging**
