### PR TITLE
Add example how to make the main window transparent

### PR DESCRIPTION
**Pull request by egribnau**
At your request, the example.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Seems good for me!

What about you @EPashkin?

**Comment by EPashkin** [comment]
Thanks, @egribnau 
I check how it work in two hour before vote.

**Comment by GuillaumeGomez** [comment]
I'll check as well, but just to see the transparent background. :D

**Comment by EPashkin** [comment]
Cool red semitransparent window.
Strange, that it size bigger that header, 👍 anyway.

**Pull request merged**
