### PR TITLE
Don't use recursive main loops for the dialogs

### PR DESCRIPTION
**Pull request by sdroege**
Recursive main loops can cause interesting reentrancy issues with e.g.
mutexes or refcells and are generally not a good idea.

See also https://github.com/gtk-rs/gtk/issues/952.

----

CC @sprang

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
This is a super weird bug...

**Comment by sdroege** [comment]
> This is a super weird bug...

Well, this PR is a good idea regardless of the bug :)

**Comment by GuillaumeGomez** [comment]
Indeed. I'll merge it once CI passed.

**Comment by sdroege** [comment]
@GuillaumeGomez green now :)

**Comment by GuillaumeGomez** [comment]
Merged now. :)

**Pull request merged**
