### PR TITLE
Merge pending to master

### PR DESCRIPTION
**Pull request by EPashkin**
For new release

cc @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Oh right, well saw! Thanks a lot! (just waiting for CI and then let's merge!)

**Comment by EPashkin** [comment]
It will be long wait at minimum for appveyor as too many crates wanting CI too 😉

**Comment by GuillaumeGomez** [comment]
Erf, I'm gonna play zelda botw a bit while waiting then. 😛

**Comment by EPashkin** [comment]
@GuillaumeGomez, @ironman-machine is your bot?
Can it be teached to do some CI?

**Comment by GuillaumeGomez** [comment]
I only use its github api key. But its primary purpose was to make a build queue for CI. So I can modify it in order to match our needs. I intended to do it since a while but still didn't find time yet...

**Comment by EPashkin** [comment]
Understand.
I while talking about CI I always forgot that we can't use it for prerelease crate check (as `cargo` don't like unpublished crates).

**Comment by GuillaumeGomez** [comment]
Unfortunately... :-/

**Comment by GuillaumeGomez** [comment]
But I at least intend to allow contributors to merge PRs through commands like "r+" just like on rust so you don't depend 100% on me.

**Comment by EPashkin** [comment]
Also not sure that "ironman-machine" can be changed to your "everyday" needs without problems with base functionality.
While "r+" is will be good, but for "everyday" needs I mostly mean cases when changes 2 or more crates need test together.
I think it can be done trough creating repository, that contains all you crates as submodules, and CI configuration to build examples as test.
Bot by command from both PRs need create one new branch in this CI repo, fetch PRs to it and then push branch to server to start CI.
When CI complete bot need send message to source PRs and maybe do some other actions (like merge).

**Comment by GuillaumeGomez** [comment]
Yes, it's a lot of work anyway so I won't start until I have enough time ahead.

**Pull request merged**
