### PR TITLE
Rename build.sh to build_travis.sh

### PR DESCRIPTION
**Pull request by EPashkin**
Fix inconsistency mentioned by @bitemyapp in https://github.com/gtk-rs/examples/pull/161.

This will need PR to other 10 (or 11 if count https://github.com/gtk-rs/tests) crates,
so I not fully sure that it really needed.

cc @GuillaumeGomez, @sdroege, @antoyo

### CODE REVIEW

**Comment by sdroege** [comment]
Sounds good to me

**Comment by GuillaumeGomez** [comment]
You changed the rights of the file too, which makes it impossible to be executed (or at least not like this).

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks, I fixed blunder.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by EPashkin** [comment]
@GuillaumeGomez I skipped `tests` repo, as no one has it fork.
All others linked here.

**Pull request merged**
