### PR TITLE
Add basic application example

### PR DESCRIPTION
**Pull request by tones111**
Attempts to address issue #79.  I created the glade file with the intent that it could be shared between the two "basic" examples.  It would be nice to keep a non-builder example and I left basic.rs as is to allow others to compare against to see the differences between the two styles.

### CODE REVIEW

**Comment by EPashkin** [comment]
:+1: after AppVeyor.
Seems we need manual change `gio::Application::run` to accept normal program arguments.
Or wait for function type rewriting (aka https://github.com/gtk-rs/gir/issues/264) and do it in config.

**Comment by gkoz** [comment]
Since `g_application_run` ignores `argc` and `argv` on Windows it may be a good idea to implement it manually passing the arguments on `!windows`.

**Comment by jabl** [comment]
Is there some major issue preventing this PR from being merged? Or, can I help somehow?

I was struggling with creating a gtk::Application hello world example myself, and when I finally managed to get everything working I thought I'd create a pull request myself so other people don't have to do the same, until I noticed at the last moment that there is already a pending pull request doing more or less the same. (My example at https://github.com/jabl/gtk-rs-sandbox/tree/master/gtkapplication or fixed up for a pull request at https://github.com/jabl/gtk-rs-examples/blob/gtkapplication/src/gtkapplication.rs .)

**Comment by GuillaumeGomez** [comment]
This one starts to get old but since the problematic function call has been removed, nothing prevents it to get merged now. If @tones111 fix the conflicts, it'll be fine by me.

**Comment by EPashkin** [comment]
Maybe https://github.com/gtk-rs/examples/pull/98#issuecomment-229383338 is still valid

**Comment by GuillaumeGomez** [comment]
Oh damn, I was looking for `g_application_run`, not `app.run`. Then no, this PR isn't suitable to get merged. (Thanks @EPashkin!)

@jabl: If you have a suitable example for all supported platforms, feel free to make a PR to add it. We'd be very happy to review it!

**Comment by jabl** [comment]
Well, my example also uses app.run(), with the attendant ugliness to massage std::env::args() into a pseudo-C shape that app.run() likes. In fact, being a more or less a Rust noob, this was probably one of the parts I struggled the most with, hence why I wanted to document it for posterity. :)

I guess this is what you meant by "isn't suitable to get merged"?

Another thing I noticed, was that now Application::new takes a &str whereas when I originally worked on my example 10 days ago it took an Option<&str>. Progress, I suppose.. :)

**Comment by GuillaumeGomez** [comment]
@jabl: Any progress on this?

**Comment by jabl** [comment]
No, I thought that since my example used app.run() you weren't interested, so I haven't done anything to it. Or did I misunderstand you?

**Comment by GuillaumeGomez** [comment]
If we weren't interested, we'd have close this PR. :)

**Comment by jabl** [comment]
Ok, great, I'll try to get something in shape with current rust/gtk-rs etc. then.

**Comment by sdroege** [comment]
There's a small example here if that helps anything: https://github.com/chergert/hello/blob/master/rust/src/main.rs

**Comment by GuillaumeGomez** [comment]
Closing due to inactivity. Don't hesitate to reopen once updated. :)

**Pull request closed without merging**
