### PR TITLE
Fix examples with get_text()

### PR DESCRIPTION
**Pull request by sophie-h**
gtk-rs/gtk#999

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I think you forgot `src\bin\listbox_model.rs`. ;)

**Comment by sophie-h** [comment]
ListBoxes are to new for skipping --all-features :roll_eyes:. Hopefully fixed now.

**Comment by GuillaumeGomez** [comment]
No problem. ;) Thanks for doing it!

**Comment by EPashkin** [comment]
```
error[E0308]: mismatched types

   --> src/bin/listbox_model.rs:154:24

    |

154 |                 if let Some(text) = entry.get_text() {

    |                        ^^^^^^^^^^   ---------------- this expression has type `glib::GString`

    |                        |

    |                        expected struct `glib::GString`, found enum `std::option::Option`

    |

    = note: expected struct `glib::GString`

                 found enum `std::option::Option<_>`

error: aborting due to previous error
```

**Comment by sdroege** [comment]
@GuillaumeGomez Can you do the CI change and merge? This breaks all CI right now :)

**Pull request merged**
