### PR TITLE
Build with the maximum versions required for each configuration on th…

### PR DESCRIPTION
**Pull request by sdroege**
…e CI of the dependant crates

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
@EPashkin why does the 3.22.30 bundle have GLib 2.55 and not 2.56, and the 3.24 bundle also instead of 2.58?

**Comment by GuillaumeGomez** [comment]
Dark magic once again.

**Comment by EPashkin** [comment]
@sdroege because on https://packages.ubuntu.com/bionic/libgtk-3-0 gtk3.22.30=>libglib2.0-0 (>= 2.55.2),
and for https://packages.ubuntu.com/disco/libgtk-3-0 too.
As I remember I has problem with glib 2.56

**Comment by sdroege** [comment]
2.55 is an unstable development release though :) And you should ideally always use the releases that were part of the relvent GNOME release, which are the version numbers I mentioned above. The dependencies in Ubuntu are not necessarily correct.

**Comment by EPashkin** [comment]
Ubuntu is fastest source that I can find, trying to build.
Also I want change packages name to just gtk-3.22.30

**Comment by sdroege** [comment]
> Ubuntu is fastest source that I can find, trying to build.

Sure but that also has 2.56 here: https://packages.ubuntu.com/bionic/libglib2.0-0
My point is that those versions in the dependencies shouldn't be trusted, not that you shouldn't use Ubuntu :)

**Comment by sdroege** [comment]
@EPashkin So what should we do here? Is there a problem with updating the versions as they are now in the `Cargo.toml`?

**Comment by EPashkin** [comment]
I preparing bootstraps with version from cargo toml,
so IMHO better wait, as I test build here too.

**Comment by EPashkin** [comment]
gtk-3.22.30 is done, 
on 3.24 I need time to understand how to include https://download.gnome.org/sources/atk/2.30/atk-2.30.0.tar.xz, it uses meson+ninja

**Comment by sdroege** [comment]
> it uses meson+ninja

You can install meson via pip if your distro doesn't have it. That also brings ninja then.

Then do

```
mkdir builddir && cd builddir
meson --prefix=/foo/bar ..
ninja
ninja install
```

meson is like the configure part, so if you had more things set than prefix do it there.

**Comment by EPashkin** [comment]
@sdroege Thanks, I missed that build dir need created before.

**Comment by EPashkin** [comment]
appveyor still use `gtk_3_20`

**Comment by sdroege** [comment]
> appveyor still use `gtk_3_20`

Oops. Will fix later :)

**Comment by sdroege** [comment]
> Oops. Will fix later :)

Fixed now already. Should all become green once the bundles are ok

**Comment by sdroege** [comment]
@EPashkin let me know when things should be retried or if you run into other problems :)

**Comment by EPashkin** [comment]
@sdroege Thanks, but I can restart job yourself, while don't have write access to repo 😉

**Comment by sdroege** [comment]
> @sdroege Thanks, but I can restart job yourself, while don't have write access to repo wink

Oh indeed. Interesting :)

**Comment by EPashkin** [comment]
@sdroege Please add     `- libmount-dev` to travis.
If travis passed, please, not merge PR, package still not finished.

**Comment by sdroege** [comment]
> @sdroege Please add `- libmount-dev` to travis.

Done

**Comment by EPashkin** [comment]
3.24 passed.
Seems we need update all .travis again no add `libmount-dev` or install it in build.sh here.

**Comment by sdroege** [comment]
>  Seems we need update all .travis again to add `libmount-dev` or install it in build.sh here.

`.travis.yml` everywhere. We can't install it in `build.sh`, and we don't have any template `.travis.yml` :( You send the PRs for that?

**Comment by EPashkin** [comment]
Ok, I do it later today.

**Comment by sdroege** [comment]
@GuillaumeGomez apart from that, this is ready to go and then we need new PRs for everything once again.

**Comment by GuillaumeGomez** [comment]
> then we need new PRs for everything once again.

Ready, I am!

**Pull request merged**
