### PR TITLE
Prepare for `Into<Option<&str>>`

### PR DESCRIPTION
**Pull request by EPashkin**
Prerequisite of https://github.com/gtk-rs/gtk/pull/446
Normally that build fails

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@EPashkin: BTW, I'll close your PR and open mine for the gtk update so we have the correct commit hash in the header (and it's been a while I didn't contribute in gtk :'( ).

**Comment by EPashkin** [comment]
Ok if you want do it yourself.
I prepared to update my PR and only need push after merging this.
Other affected `gio`, `glib`

**Comment by EPashkin** [comment]
Better merge this and restart CI for your PR

**Comment by GuillaumeGomez** [comment]
Thanks for this update!

**Pull request merged**
