### PR TITLE
Gir files zesty

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir-files/issues/1

WIP just features template

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I don't really understand this PR. What is it doing?

**Comment by EPashkin** [comment]
It just template, after crates published we need update travis script to higher version, so need higher version dependence.
I think just uncomment nondefault versions and remove duplicates.
As we currently don't have `gtk_3_18` examples so may be better just change it to `gtk_3_22` or so.

**Comment by GuillaumeGomez** [comment]
Then please do and Ill merge.

**Comment by EPashkin** [comment]
Not sure that it good idea merge it before checking that `gtk_3_22` will work on both travis and appveyor.
And this can be done without crates :(
But if you like, I can update.
Just change 18 to 22 ?

**Comment by GuillaumeGomez** [comment]
Yes please! :) We'll see what travis and appveyor says.

**Comment by EPashkin** [comment]
Updated

**Comment by EPashkin** [comment]
Seems travis stays on 3,18, until @gkoz prepared new bundle.

**Comment by GuillaumeGomez** [comment]
Erf, not cool. :-/

**Comment by GuillaumeGomez** [comment]
Well, should I merge or not then?

**Comment by EPashkin** [comment]
IMHO better wait for appveyour and change travis back to 18

**Comment by EPashkin** [comment]
v22 not builds well (good thing that it start building, sooner it fail on unknown feature "gtk/v3_22"),
```
error[E0277]: the trait bound `str: glib::translate::ToGlibPtr<'_, *mut *const i8>` is not satisfied
   --> D:/eap/rust/0/gtk\src\auto\file_chooser.rs:176:122
    |
176 |             ffi::gtk_file_chooser_add_choice(self.to_glib_none().0, id.to_glib_none().0, label.to_glib_none().0, options.to_glib_none().0, option_labels.to_glib_none().0);
    |                                                                                                                          ^^^^^^^^^^^^ the trait `glib::translate::ToGlibPtr<'_, *mut *const i8>` is not implemented for `str`
    |
    = help: the following implementations were found:
    = help:   <str as glib::translate::ToGlibPtr<'a, *const i8>>
    = help:   <str as glib::translate::ToGlibPtr<'a, *mut i8>>

error[E0277]: the trait bound `str: glib::translate::ToGlibPtr<'_, *mut *const i8>` is not satisfied
   --> D:/eap/rust/0/gtk\src\auto\file_chooser.rs:176:154
    |
176 |             ffi::gtk_file_chooser_add_choice(self.to_glib_none().0, id.to_glib_none().0, label.to_glib_none().0, options.to_glib_none().0, option_labels.to_glib_none().0);
    |                                                                                                                                                          ^^^^^^^^^^^^ the trait `glib::translate::ToGlibPtr<'_, *mut *const i8>` is not implemented for `str`
    |
    = help: the following implementations were found:
    = help:   <str as glib::translate::ToGlibPtr<'a, *const i8>>
    = help:   <str as glib::translate::ToGlibPtr<'a, *mut i8>>
```

**Comment by GuillaumeGomez** [comment]
Strange failure. :-/

**Comment by EPashkin** [comment]
Both parameters has strange type `<type name="utf8" c:type="const char**"/>` and I can't find function in https://developer.gnome.org/gtk3/3.22/GtkFileChooser.html
So IMHO better just ignore this function now

**Comment by GuillaumeGomez** [comment]
Maybe they did an error when creating the gir files, who knows...

**Comment by EPashkin** [comment]
Second error:
```
error[E0034]: multiple applicable items in scope
  --> src\notebook.rs:27:16
   |
27 |         button.set_focus_on_click(false);
   |                ^^^^^^^^^^^^^^^^^^ multiple `set_focus_on_click` found
   |
   = note: candidate #1 is defined in an impl of the trait `gtk::ButtonExt` for the type `_`
   = note: candidate #2 is defined in an impl of the trait `gtk::ComboBoxExt` for the type `_`
   = note: candidate #3 is defined in an impl of the trait `gtk::WidgetExt` for the type `_`
```
In '3.20' this function was added to widget, so it conflicts (don't understand why `ComboBoxExt` in list for `Button`)

**Comment by GuillaumeGomez** [comment]
Ah damn. When using a trait method, maybe we should do:

```rust
Trait::method(self, params);
```

Don't you think?

**Comment by EPashkin** [comment]
Changed, seems now it all builds

**Comment by EPashkin** [comment]
IMHO `Trait::method(..)` better used only in "strange" cases

**Comment by GuillaumeGomez** [comment]
Ok, let's see the outcome!

**Comment by EPashkin** [comment]
Apveyour has 3.20, updated

**Comment by GuillaumeGomez** [comment]
Tests passed, I merge. Thanks!

**Pull request merged**
