### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@sdroege: Weird error for subclassing:

```
Compiling gobject-subclass v0.3.0 (https://github.com/gtk-rs/gobject-subclass#0248dcdc)
error: no rules expected the token `>`
   --> C:\Users\appveyor\.cargo\git\checkouts\gobject-subclass-3782bfbcef65f179\0248dcd\gobject-subclass\src\object.rs:523:52
    |
523 |     pub struct Object(Object<InstanceStruct<Object>>);
    |                                                    ^ no rules expected this token in macro call
error: aborting due to previous error
error: Could not compile `gobject-subclass`.
```

**Comment by EPashkin** [comment]
@GuillaumeGomez Remove merging master to pending first.
object_subclass uses old macros

**Comment by sdroege** [comment]
> Compiling gobject-subclass

Nothing should depend on this anymore, it's obsolete after having merged all that into glib itself.

**Comment by GuillaumeGomez** [comment]
Makes sense.

**Comment by sdroege** [comment]
Good to go once it builds then :)

**Comment by EPashkin** [comment]
I suggest hard reset current pending branch to dd614118372f82eb7651a032a2fdb5ec4d058566 and master to f802d6479803690d16c67e5378ea9a7771e791ac,
then restart CI here and in my PR,
after this we can merge pending to master again.

**Comment by EPashkin** [comment]
* after its merged

**Pull request merged**
