### PR TITLE
Fix call TreeModel.get_path

### PR DESCRIPTION
**Pull request by EPashkin**
For good build of https://github.com/gtk-rs/gtk/pull/279

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems `CONTRIBUTING.md` need change.

**Comment by GuillaumeGomez** [comment]
To be completed as least. I merge your PR, it's useless to wait for it to complete. Thanks!

**Comment by gkoz** [comment]
I believe `CONTRIBUTING.md` is fine and this should've gone into the `pending` branch.

**Comment by EPashkin** [comment]
Missed that test get `pending` branch

**Pull request merged**
