### PR TITLE
Add async/await GIO example

### PR DESCRIPTION
**Pull request by sdroege**
This depends on https://github.com/gtk-rs/glib/pull/325 and is on top of https://github.com/gtk-rs/examples/pull/166

### CODE REVIEW

**Comment by sdroege** [comment]
CI has to be restarted now that the glib part is merged @GuillaumeGomez

**Comment by EPashkin** [comment]
As expected await version lock more simple.
Thanks.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
Great, now all pieces are in :) expect a blog post with more examples later or tomorrow

**Pull request merged**
