### PR TITLE
Merge pending into master

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir-files/issues/1

### CODE REVIEW

**Comment by EPashkin** [comment]
cc @GuillaumeGomez 
Travis nightly fails due network error.

**Comment by EPashkin** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I restarted travis many time. Let's go for another round! :)

**Comment by GuillaumeGomez** [comment]
Still failing for some reasons...

**Comment by EPashkin** [comment]
Hm, then it not network error.

**Comment by EPashkin** [comment]
Do not merge if pass

**Comment by EPashkin** [comment]
Interesting, why only nightly
```
Caused by:

  [16/-17] The SSL certificate is invalid
```

**Comment by GuillaumeGomez** [comment]
Ah right! Cargo has/had an issue with openssl!

**Comment by EPashkin** [comment]
You right: https://github.com/rust-lang/cargo/issues/3346
I undo `-v`

**Comment by EPashkin** [comment]
@GuillaumeGomez, please, restart build

**Comment by GuillaumeGomez** [comment]
Done.

**Comment by GuillaumeGomez** [comment]
Ping me once it's okay if I forget.

**Comment by EPashkin** [comment]
CI finished

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
