### PR TITLE
Add grid example

### PR DESCRIPTION
**Pull request by EPashkin**
Example for grid child properties https://github.com/gtk-rs/gtk/pull/395

### CODE REVIEW

**Comment by EPashkin** [comment]
cc @GuillaumeGomez

**Comment by EPashkin** [comment]
I was too fast, other PR still not merged

**Comment by GuillaumeGomez** [comment]
Now it is, I restart CIs.

**Comment by EPashkin** [comment]
Ping

**Comment by GuillaumeGomez** [comment]
My bad, forgot this one. Thanks!

**Pull request merged**
