### PR TITLE
Pending

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Arf, going to fix conflicts by hand then.

**Comment by GuillaumeGomez** [comment]
I *think* it's good.

**Comment by EPashkin** [comment]
Strange diff

**Comment by EPashkin** [comment]
Seems you need do it by hand too with merging from your master

**Comment by GuillaumeGomez** [comment]
I think I broke it a bit and I don't have a local copy. Do you have one? (if so I'll clone your repo)

**Comment by EPashkin** [comment]
Pushed old Pending and master branches to https://github.com/EPashkin/examples

**Comment by GuillaumeGomez** [comment]
Ok, so now we're back to the old issue.

**Comment by GuillaumeGomez** [comment]
And now it's ever more strange. Damn. I can't rebase on master, I can't merge master in here and I can't merge this into while having a PR open. Did I miss something?

**Comment by EPashkin** [comment]
IMHO you need manual merge pending to master in your clone, then edit this PR to merge your master

**Comment by GuillaumeGomez** [comment]
Ok so I'll just merge by hand.

**Comment by GuillaumeGomez** [comment]
And done, no PR. :-/

**Comment by EPashkin** [comment]
Removed CONTRIBUTING.md, cargo.toml link to git, suspious change in appveyor badge

**Comment by GuillaumeGomez** [comment]
And damn.

**Comment by GuillaumeGomez** [comment]
CONTRIBUTING.md isn't in pending branch either. Strange no?

**Comment by EPashkin** [comment]
It only on master to warning about that wrong PR to master

**Comment by GuillaumeGomez** [comment]
Aaaaaah! That's why...

**Pull request closed without merging**
