### PR TITLE
Use reexported cairo enums

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/cairo/pull/217

cc @GuillaumeGomez , @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Nice! I'll restart the CI here once the cairo PR is merged.

**Comment by EPashkin** [comment]
Seems CI will pass on current cairo too.

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
