### PR TITLE
Add example builder_signal

### PR DESCRIPTION
**Pull request by sfanxiang**
__Requires__ gtk-rs/gtk#852.

cc @EPashkin @GuillaumeGomez @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by EPashkin** [comment]
@sfanxiang Please "Edit" PR: it need be against "pending" branch

**Comment by GuillaumeGomez** [comment]
I changed the target branch.

**Comment by sfanxiang** [comment]
> I changed the target branch.

Thanks @GuillaumeGomez.

**Comment by EPashkin** [comment]
👍

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
