### PR TITLE
RadioButton example v2

### PR DESCRIPTION
**Pull request by zzeroo**
Second try to contribute a Radio Button example.

This example was an answer to a users question on gitter.

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez, IMHO this better not be merged until we decide what to do with https://github.com/gtk-rs/gtk/issues/488

**Comment by EPashkin** [comment]
@zzeroo Thanks.
Instead recreating PR you can edit PR title and change target branch.

**Comment by GuillaumeGomez** [comment]
I agree. Quite problematic.

**Comment by GuillaumeGomez** [comment]
Closing due to inactivity. Don't hesitate to reopen once updated. :)

**Pull request closed without merging**
