### PR TITLE
Add clone macro example

### PR DESCRIPTION
**Pull request by antoyo**

### CODE REVIEW

**Comment by sdroege** [comment]
The example can be merged as-is once https://github.com/gtk-rs/glib/pull/527 is in

**Comment by sdroege** [comment]
@antoyo @GuillaumeGomez needs to be rebased on top of latest pending to succeed the build.

**Comment by antoyo** [comment]
@sdroege: I rebased on top of pending, but there's a conflict with master.
Did I do anything wrong?

**Comment by sdroege** [comment]
The PR is against master now, but it should be against pending.

**Comment by sdroege** [comment]
@antoyo Thanks!

**Pull request merged**
