### PR TITLE
basic_subclass: fix name of our GObject subclasss type

### LINKED ISSUE #307: in basic_subclass exmaple, the Private struct is exposed to gtk
As discussed in https://github.com/gtk-rs/examples/issues/279#issue-542074234

>  Shouldn't be it SimpleWindow instead of the SimpleWindowPrivate in the inspector?

https://user-images.githubusercontent.com/6001248/71407718-22aedd80-263c-11ea-9743-06d5f58770f1.png

### PR DESCRIPTION
**Pull request by alatiera**
Close #307

### CODE REVIEW

**Comment by alatiera** [comment]
cc @sdroege I think this is correct but not entirerly sure. The name constant there corresponds to what we would set with ClassName in C right?

**Comment by sdroege** [comment]
> The name constant there corresponds to what we would set with ClassName in C right?

Yes. That's why I usually do things different than you did here. An `imp` module with `struct Foo` for the implementation, and outside the `imp` module a `struct Foo` for the public type. This way you don't have the confusion about type names and can distinguish between the two via `imp::Foo` and `super::Foo`.

**Comment by alatiera** [comment]
done as well, I think its from when I initially had implemented the functions on the public struc.

**Comment by sdroege** [comment]
Looks good to me, @GuillaumeGomez please merge when green :)

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
@GuillaumeGomez green

**Comment by GuillaumeGomez** [comment]
Thanks @alatiera !

**Pull request merged**
