### PR TITLE
Fix build with latest glib API changes

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
Fixed problem with read_async.
I also get errors with sub-classing, seems travis need build it for 3.18+ too
```
error: no rules expected the token `>`
   --> src\bin\listbox_model.rs:367:126
    |
367 |         pub struct RowData(Object<subclass::simple::InstanceStruct<imp::RowData>, subclass::simple::ClassStruct<imp::RowData>>);
    |                                                                                                                              ^ no rules expected this token in macro call

error[E0432]: unresolved import `row_data::RowData`
  --> src\bin\listbox_model.rs:25:5
   |
25 | use row_data::RowData;
   |     ^^^^^^^^^^^^^^^^^ no `RowData` in `row_data`

warning: unused import: `glib::translate::*`
   --> src\bin\listbox_model.rs:258:9
    |
258 |     use glib::translate::*;
    |         ^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(unused_imports)] on by default
```

**Comment by sdroege** [comment]
>  I also get errors with subclassing, seems travis need build it for 3.18+ too

That one is fixed now, thanks.

**Comment by EPashkin** [comment]
@sdroege Thanks, now it builds for me locally
Can you add "subclassing" to build_travis.sh too? For both "3.22.30" and "3.18"

**Comment by sdroege** [comment]
>  Can you add "subclassing" to build_travis.sh too? For both "3.22.30" and "3.18"

Done :)

**Comment by EPashkin** [comment]
Thanks

**Comment by EPashkin** [comment]
Restarting travis

**Comment by EPashkin** [comment]
And CI passed 🎉

**Comment by GuillaumeGomez** [comment]
Yeay! Thanks @sdroege!

**Pull request merged**
