### PR TITLE
Update for removal of ObjectImpl::get_type_data()

### PR DESCRIPTION
**Pull request by sdroege**
CC @EPashkin @GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Please restart CI here

**Comment by GuillaumeGomez** [comment]
Done!

**Comment by EPashkin** [comment]
Strange that CI failing,  @sdroege  something is not merged?

**Comment by EPashkin** [comment]
Also here one old warning in changed files:
```
warning: unused import: `glib::subclass::prelude::*`
  --> src\bin\basic_subclass.rs:21:5
   |
21 | use glib::subclass::prelude::*;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted
```

**Comment by sdroege** [comment]
Hmm, did I forgot something? Let's see.

**Comment by sdroege** [comment]
Fixed the warning but the CI failure is simply because it uses an old version of glib for some reason. It builds fine here.

**Comment by EPashkin** [comment]
@sdroege Please change target branch to pending

**Comment by sdroege** [comment]
Ah that was the problem. Thanks :)

**Comment by EPashkin** [comment]
Seems CI need restarted again, Travis still think that it against master

**Comment by GuillaumeGomez** [comment]
Let's see now. :)

**Comment by sdroege** [comment]
Looks good now, thanks :)

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
