### PR TITLE
Upcast return value of the bind_model() closure in listbox_model.rs e…

### PR DESCRIPTION
**Pull request by sdroege**
…xample

### CODE REVIEW

**Comment by sdroege** [comment]
Depends on https://github.com/gtk-rs/examples/pull/224

**Comment by EPashkin** [comment]
👍

**Comment by sdroege** [comment]
@GuillaumeGomez please kick the CI here once the GTK PR is merged, and then it should all be green again.

**Comment by GuillaumeGomez** [comment]
Restarted CI.

**Comment by sdroege** [comment]
@GuillaumeGomez please merge then :)

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
