### PR TITLE
Fix build of the examples

### PR DESCRIPTION
**Pull request by sdroege**
@GuillaumeGomez 

Part of gtk-rs/sys#152.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks! Will wait for CI for this one to confirm everything built as expected.

**Comment by sdroege** [comment]
@GuillaumeGomez Fails because pangocairo is broken :)

**Comment by GuillaumeGomez** [comment]
Fixing it. ;)

**Comment by sdroege** [comment]
@GuillaumeGomez All green!

**Pull request merged**
