### PR TITLE
Use gtk/v3_22_30

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/examples/pull/173

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1: (just waiting for CI)

**Comment by EPashkin** [comment]
Hm, seems futures_nightly is compiles now, I try to enable it

**Comment by sdroege** [comment]
> Hm, seems futures_nightly is compiles now, I try to enable it

A miracle!

**Comment by GuillaumeGomez** [comment]
Or a bug, we're never too sure with futures... :stuck_out_tongue:

**Comment by EPashkin** [comment]
CI passed with futures_nigthly,
@sdroege, @GuillaumeGomez we merge or still use futures_stable?

**Comment by GuillaumeGomez** [comment]
I let that decision up to @sdroege. Meanwhile I merge this one. :)

**Comment by sdroege** [comment]
Let's merge, then we notice at least once it is broken again

**Pull request merged**
