### PR TITLE
Travis fix

### PR DESCRIPTION
**Pull request by EPashkin**
Attempt to fix memory kills in travis

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez Please restart this PR on travis

**Comment by GuillaumeGomez** [comment]
It didn't start. Do we even test on pending?

**Comment by EPashkin** [comment]
Hm, merged PR's shows that we have ;)
I see only failed appveyours for this. Maybe it fail because I make PR on master branch and then fast edited PR to fix it.

**Comment by EPashkin** [comment]
Ok, repushed branch and all restarted

**Comment by EPashkin** [comment]
Hm, travis log looks strange: certificate update, etc.
Compare with https://travis-ci.org/gtk-rs/examples/builds/242071356?utm_source=github_status&utm_medium=notification

**Comment by EPashkin** [comment]
Seems it passed https://travis-ci.org/gtk-rs/examples/builds/256115154?utm_source=github_status&utm_medium=notification

**Comment by GuillaumeGomez** [comment]
Yeay! Just waiting to see your macro change and then I merge.

**Comment by EPashkin** [comment]
Added quick fix for unused macro in `grid.rs`.
Bad that we don't know if previous builds on example is actually failing :(
But can test it on https://github.com/gtk-rs/sys/pull/57 after this merged

**Comment by EPashkin** [comment]
Hm, now travis workers seems returned back.
@GuillaumeGomez, please try restart travis on https://github.com/gtk-rs/sys/pull/57

**Comment by EPashkin** [comment]
Question, what better use current version and add "-j 1" to all travis.yml.
Or made it hard coded to build.sh ?

**Comment by EPashkin** [comment]
@GuillaumeGomez, @sdroege What you prefer: hard coded "-j 1" in `build.sh` in this repo or add it to call in each `.travis.yml`?

**Comment by GuillaumeGomez** [comment]
I'd prefer to have in here only. Easier to update it when needed.

**Comment by EPashkin** [comment]
@sdroege, your opinion about this?

**Comment by EPashkin** [comment]
@GuillaumeGomez updated to single-change.
Travis passed.
When you merge, please restart travis on https://github.com/gtk-rs/sys/pull/57

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
