### PR TITLE
Add hint

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by gkoz** [comment]
Now that `FileError` is exported properly this can be 
```rust
            if e.matches::<glib::FileError>() == Some(glib::FileError::Noent) {
                println!("Try relaunching this example from the same level as \
                         the `resources` directory.");
            }
```

I wonder though if `matches` should be changed to `typed` for consistency with `Value`...

**Comment by GuillaumeGomez** [comment]
And we should also think to make errors' name more verbose. Quite difficult to understand for now.

**Comment by gkoz** [comment]
Yeah, the `FileError` is a mess. It should look closer to `std::io::ErrorKind`. Maybe there could even be conversions between them...

**Comment by GuillaumeGomez** [comment]
http://blog.burntsushi.net/rust-error-handling/#error-handling-with-a-custom-type ?

**Comment by gkoz** [comment]
A single enum works for a closed hierarchy. We have an open one here: any library can define additional error domains.

**Comment by gkoz** [comment]
So, the above code would now be
```rust
            if e.typed::<glib::FileError>() == Some(glib::FileError::Noent) {
                println!("Try relaunching this example from the same level as \
                         the `resources` directory.");
            }
```

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by gkoz** [comment]
Thanks

**Pull request merged**
