### PR TITLE
Fix converting generated enums to i32

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
Its first part of `enum as i32`

**Comment by gkoz** [comment]
You'll probably have to make this PR independent: I don't think the menubar PR should be using a generic dialog so the `as i32` patch probably won't touch it.

**Comment by EPashkin** [comment]
k

**Comment by EPashkin** [comment]
Done

**Comment by EPashkin** [comment]
AppVeyor build succeeded, @gkoz, please, merge this and I prepare last part

**Comment by GuillaumeGomez** [comment]
I'll merge since I don't see any issue. We'll go back on it if there are. Thanks @EPashkin!

**Pull request merged**
